spring:
  application:
    name: job-posting-service

  datasource:
    url: jdbc:postgresql://localhost:5432/pickbit_job_db
    username: pickbit_user
    password: pickbit_pass_2024
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/view-history-constraint.sql

scheduler:
  job-posting:
    fixed-rate: 300000
  view-history:
    fixed-rate: 1000
  main-page:
    fixed-rate: 600000