services:
  postgres:
    image: postgres:17
    container_name: pickbit-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pickbit_job_db
      POSTGRES_USER: pickbit_user
      POSTGRES_PASSWORD: pickbit_pass_2024
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: pickbit-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data: